language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
script:
  - python setup.py build_ext
  - python setup.py bdist_egg
deploy:
  provider: pypi
  username: trovao
  distributions: sdist bdist_egg
  edge: true
  on:
    tags: true
